spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oawt2el4dBOKfknp4x6
            client-secret: ZWXgnMk1B21gRVFjOSS44ZDqiK_TR5O_1jTXCI9c
            client-name: Okta
          provider:
            okta:
              issuer-uri: https://dev-176965.okta.com/oauth2/default
